name: 'Install Swift toolchain'
description: 'Install Swift toolchain tarball from URL'
inputs:
  download-url:
    description: 'URL to download Swift toolchain tarball'
    required: true

runs:
  using: composite
  steps:
    # https://www.swift.org/install/linux/#installation-via-tarball
    - name: Install dependent packages for Swift
      shell: bash
      run: >
        sudo apt-get -q update &&
        sudo apt-get install -y
        binutils
        git
        gnupg2
        libc6-dev
        libcurl4-openssl-dev
        libedit2
        libgcc-9-dev
        libpython3.8
        libsqlite3-0
        libstdc++-9-dev
        libxml2-dev
        libz3-dev
        pkg-config
        tzdata
        unzip
        zlib1g-dev
        curl

    - name: Install Swift
      shell: bash
      run: curl -fL ${{ inputs.download-url }} | sudo tar xfz - --strip-components=2 -C /usr/local
